name: Dev Build

on:
  push:
    branches:
      - dev
    paths:
      - '**/*.java'
      - '**/application.properties'
      - '**/resources/*'
      - '*.gradle'

jobs:
  build:
    name: Build Service Jar
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew bootJar

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: service-jar
          path: build/libs/*.jar